services:
  menumkr:
    image: node:18
    container_name: menumkr-node
    working_dir: /app
    entrypoint: /app/.docker/entrypoint-node.sh
    ports:
      - '9000:9000'
    volumes:
      - ./:/app
