services:
  menumkr:
    image: node:18
    container_name: menumkr-node
    working_dir: /app
    entrypoint: /app/.docker/entrypoint-node.sh
    ports:
      - '9100:9100'
      - '24678:24678'
    volumes:
      - ./:/app
